const labels = {
  homepage: {
    gestioneReferti: "Gestione Referti",
    elencoRegistrazioni: "Elenco Registrazioni",
    prestazioniRisultati: "Prestazioni",
  },
  elencoRegistrazioni: {
    dataRitiro: "Data Ritiro",
    del: "Del",
    cognome: "Cognome",
    nome: "Nome",
    eta: "Età",
    codice: "Codice",
    settori: "Settori",
    creataDa: "Creata da",
    examinationWorkflowNote: "Nota Prel.",
  },
  gestioneReferti: {
    filtriDiRicerca: "Filtri di Ricerca",
    dataDa: "Data da:",
    dataA: "Data a:",
    periodo: "Periodo:",
    medico: "",
    settori: "Settori",
    unitaOperative: "Unità Operative",
    tutti: "Tutti",
    interrograPerDataRitiro: "Per data Ritiro",
    includiRefertiCompleti: "Referti Completi",
    includiPrescrizioniComplete: "Prescrizioni Complete",
    ricercaPaziente: "Ricerca Paziente",
    cognome: "Cognome:",
    nome: "Nome:",
    cerca: "Cerca",
    utilitaEPreferenze: "Utilità e Preferenze",
    prescrizione: "Prescrizione",
    anamnesi: "Anamnesi",
    documenti: "Documenti",
    note: "Note",
  },
  prestazioniRisultati: {
    codice: "Codice",
    nome: "Nome",
    descParametro: "Desc. Parametro",
    dataRitiro: "Data Ritiro",
    stato: "Stato",
    medicoEsecutore: "Medico Esecutore",
    refUnico: "Ref. Unico",
    unitaOperativa: "Unità Operativa",
    caricaFile: "Carica File",
    cancella: "Cancella",
  },
  editorPage: {
    frasiComuni: "Frasi Comuni",
    frasiComuniEspanseInizialmente: "true",
    dettatura: "Dettatura",
    esitiPrecedenti: "Esiti Precedenti",
    stampaETerminaReferto: "Stampa Referto",
    apriImmagini: "Apri Immagini",
    scaricaReferto: "Scarica Referto",
    terminaReferto: "Termina E Invia",
    confermaTerminaReferto: "Conferma Termina Referto",
    vuoiScaricare: "Vuoi scaricare il referto?",
    siScaricaETermina: "Sì, scarica e termina",
    noTermina: "No, termina senza scaricare",
    cancella: "Cancella",
    salva: "Salva",
    anteprimaPDF: "Visualizza Referto",
    annulla: "Annulla",
    dettaturaVocale: "Dettatura Vocale",
    iniziaRegistrazione: "Inizia Registrazione",
    fermaRegistrazione: "Ferma Registrazione",
    trascrizioneInCorso: "Trascrizione in corso...",
    inserisciTesto: "Inserisci Testo",
    downloadModello: "Scarica Modello Vocale",
    downloadInCorso: "Download in corso...",
    modelloNonDisponibile: "Il modello vocale non è ancora stato scaricato. Scaricarlo ora?",
    erroreRegistrazione: "Errore durante la registrazione",
    erroreWhisper: "Errore nella trascrizione vocale",
    prontoPerRegistrare: "Pronto per registrare",
    registrazioneInCorso: "Registrazione in corso...",
    nessunaTrascrizioneRilevata: "Nessun testo rilevato. Riprovare.",
    dettaturaInline: "Dettatura",
    stopDettatura: "Stop",
    dettaturaInCorso: "Dettatura in corso...",
    dettaturaModalCompleta: "Dettatura con revisione",
  },
};

export default labels;
